360test.home/Nop.Plugin.BrainStation.QuickView/Controllers/BsQuickViewController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Seo;
using Nop.Core.Domain.Vendors;
using Nop.Plugin.BrainStation.QuickView.Models;
using Nop.Services.Configuration;
using Nop.Plugin.BrainStation.QuickView.Infrastructure.Cache;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Directory;
using Nop.Services.Helpers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Media;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Shipping;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Services.Vendors;
using Nop.Web.Controllers;
using Nop.Web.Extensions;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Security;
using Nop.Web.Models.Catalog;
using Nop.Web.Models.Checkout;
using Nop.Web.Models.Media;
using Nop.Web.Framework.Security.Captcha;

namespace Nop.Plugin.BrainStation.QuickView.Controllers
{
    public class BsQuickViewController : BasePublicController
    {
        
        
        


        private readonly ICategoryService _categoryService;
        private readonly IManufacturerService _manufacturerService;
        private readonly IProductService _productService;
        private readonly IVendorService _vendorService;
        private readonly IProductTemplateService _productTemplateService;
        private readonly IProductAttributeService _productAttributeService;
        private readonly IWorkContext _workContext;
        private readonly IStoreContext _storeContext;
        private readonly ITaxService _taxService;
        private readonly ICurrencyService _currencyService;
        private readonly IPictureService _pictureService;
        private readonly ILocalizationService _localizationService;
        //change-3.7
        private readonly IMeasureService _measureService;
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IWebHelper _webHelper;
        private readonly ISpecificationAttributeService _specificationAttributeService;
        private readonly IDateTimeHelper _dateTimeHelper;
        private readonly IRecentlyViewedProductsService _recentlyViewedProductsService;
        private readonly ICompareProductsService _compareProductsService;
        private readonly IWorkflowMessageService _workflowMessageService;
        private readonly IProductTagService _productTagService;
        private readonly IOrderReportService _orderReportService;
        private readonly IBackInStockSubscriptionService _backInStockSubscriptionService;
        private readonly IAclService _aclService;
        private readonly IStoreMappingService _storeMappingService;
        private readonly IPermissionService _permissionService;
        private readonly ICustomerActivityService _customerActivityService;
        private readonly IProductAttributeParser _productAttributeParser;
        private readonly IShippingService _shippingService;
        private readonly MediaSettings _mediaSettings;
        private readonly CatalogSettings _catalogSettings;
        private readonly VendorSettings _vendorSettings;
        private readonly ShoppingCartSettings _shoppingCartSettings;
        private readonly LocalizationSettings _localizationSettings;
        private readonly CustomerSettings _customerSettings;
        private readonly CaptchaSettings _captchaSettings;
        private readonly SeoSettings _seoSettings;
        private readonly ICacheManager _cacheManager;
        private readonly ISettingService _settingService;
        private readonly IDownloadService _downloadService;


        public BsQuickViewController(
            ICategoryService categoryService,
            IManufacturerService manufacturerService,
            IProductService productService,
            IVendorService vendorService,
            IProductTemplateService productTemplateService,
            IProductAttributeService productAttributeService,
            IWorkContext workContext,
            IStoreContext storeContext,
            ITaxService taxService,
            ICurrencyService currencyService,
            IPictureService pictureService,
            ILocalizationService localizationService,
            //change-3.7
            IMeasureService measureService,
            IPriceCalculationService priceCalculationService,
            IPriceFormatter priceFormatter,
            IWebHelper webHelper,
            ISpecificationAttributeService specificationAttributeService,
            IDateTimeHelper dateTimeHelper,
            IRecentlyViewedProductsService recentlyViewedProductsService,
            ICompareProductsService compareProductsService,
            IWorkflowMessageService workflowMessageService,
            IProductTagService productTagService,
            IOrderReportService orderReportService,
            IBackInStockSubscriptionService backInStockSubscriptionService,
            IAclService aclService,
            IStoreMappingService storeMappingService,
            IPermissionService permissionService,
            ICustomerActivityService customerActivityService,
            IProductAttributeParser productAttributeParser,
            IShippingService shippingService,
            MediaSettings mediaSettings,
            CatalogSettings catalogSettings,
            VendorSettings vendorSettings,
            ShoppingCartSettings shoppingCartSettings,
            LocalizationSettings localizationSettings,
            CustomerSettings customerSettings,
            CaptchaSettings captchaSettings,
            SeoSettings seoSettings,
            ICacheManager cacheManager,
            ISettingService settingService,
            IDownloadService downloadService
            )
        {
            
            this._categoryService = categoryService;
            this._manufacturerService = manufacturerService;
            this._productService = productService;
            this._vendorService = vendorService;
            this._productTemplateService = productTemplateService;
            this._productAttributeService = productAttributeService;
            this._workContext = workContext;
            this._storeContext = storeContext;
            this._taxService = taxService;
            this._currencyService = currencyService;
            this._pictureService = pictureService;
            this._localizationService = localizationService;
            //change-3.7
            this._measureService = measureService;
            this._priceCalculationService = priceCalculationService;
            this._priceFormatter = priceFormatter;
            this._webHelper = webHelper;
            this._specificationAttributeService = specificationAttributeService;
            this._dateTimeHelper = dateTimeHelper;
            this._recentlyViewedProductsService = recentlyViewedProductsService;
            this._compareProductsService = compareProductsService;
            this._workflowMessageService = workflowMessageService;
            this._productTagService = productTagService;
            this._orderReportService = orderReportService;
            this._backInStockSubscriptionService = backInStockSubscriptionService;
            this._aclService = aclService;
            this._storeMappingService = storeMappingService;
            this._permissionService = permissionService;
            this._customerActivityService = customerActivityService;
            this._productAttributeParser = productAttributeParser;
            this._shippingService = shippingService;
            this._mediaSettings = mediaSettings;
            this._catalogSettings = catalogSettings;
            this._vendorSettings = vendorSettings;
            this._shoppingCartSettings = shoppingCartSettings;
            this._localizationSettings = localizationSettings;
            this._customerSettings = customerSettings;
            this._captchaSettings = captchaSettings;
            this._seoSettings = seoSettings;
            this._cacheManager = cacheManager;
            this._settingService = settingService;
            this._downloadService = downloadService;
        }


        


        #region Non-Action
        [NonAction]
        protected virtual IEnumerable<ProductOverviewModel> PrepareProductOverviewModels(IEnumerable<Product> products,
            bool preparePriceModel = true, bool preparePictureModel = true,
            int? productThumbPictureSize = null, bool prepareSpecificationAttributes = false,
            bool forceRedirectionAfterAddingToCart = false)
        {
            return this.PrepareProductOverviewModels(_workContext,
                _storeContext, _categoryService, _productService, _specificationAttributeService,
                _priceCalculationService, _priceFormatter, _permissionService,
                _localizationService, _taxService, _currencyService,
                _pictureService, _webHelper, _cacheManager,
                _catalogSettings, _mediaSettings, products,
                preparePriceModel, preparePictureModel,
                productThumbPictureSize, prepareSpecificationAttributes,
                forceRedirectionAfterAddingToCart);
        }

        [NonAction]
        protected virtual ProductDetailsModel PrepareProductDetailsPageModel(Product product,
                   ShoppingCartItem updatecartitem = null, bool isAssociatedProduct = false)
        {
            if (product == null)
                throw new ArgumentNullException("product");

            #region Standard properties

            var model = new ProductDetailsModel

360test.home/Nop.Plugin.BrainStation.QuickView/Views/BsQuickViewConfiguare.cshtml
@using Nop.Plugin.BrainStation.QuickView.Models
@using Nop.Web.Framework
@model BsQuickViewSettingsModel
@using Nop.Core.Domain.Seo;
@using Nop.Core.Infrastructure;
@using Nop.Web.Models.Catalog;
@using Nop.Web.Framework.UI

<!--product breadcrumb-->



@using (Html.BeginForm("Save", "Admin/Plugin/QuickView/Settings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
      @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
            @T("admin.plugin.brainstation.quickview.settings")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="k-button">@T("admin.plugin.brainstation.quickview.save")</button>
            
        </div>
    </div>
    @Html.ValidationSummary(false)
   
    <table class="adminContent">
        
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.EnableWidget") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.EnableWidget)
               
            </td>
        </tr>
<tr>
            <td colspan="2">If you check this opton you will enable the widget of the Bs Quick View plugin. Disabling the checking will make the all settings of Bs Quick View inactive.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>

        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.EnableEnlargePicture") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.EnableEnlargePicture)
               
            </td>
        </tr>
<tr>
            <td colspan="2">If you check this opton you will have a splendid view of enlarged picture on each product box items .After checking & saving it reload your main store page and hover on the product pictures in product box and see the awosomeness.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ShowAlsoPurchased") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ShowAlsoPurchased)
               
            </td>
        </tr>
<tr>
            <td colspan="2">This Option will activate showing the Products which was also purchased with the clicked product on Modal named "Customers who bought this item also bought".</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ShowRelatedProducts") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ShowRelatedProducts)
               
            </td>
        </tr>
<tr>
            <td colspan="2">This Option will activate showing the related Products on Modal.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ButtonContainerName") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ButtonContainerName)
               
            </td>
        </tr>
<tr>
            <td colspan="2">Provide the class name in which the button "Quick View" will appear. Remember add a '.' before class name . eg(.buttons)</td>
        </tr>

        

        
    </table>

   
}

360test.home/Nop.Plugin.BrainStation.QuickView/Views/BsQuickViewHelp.cshtml
@using Nop.Plugin.BrainStation.QuickView.Models
@using Nop.Web.Framework
@model BsQuickViewModel
@using Nop.Core.Domain.Seo;
@using Nop.Core.Infrastructure;
@using Nop.Web.Models.Catalog;
@using Nop.Web.Framework.UI

<!--product breadcrumb-->


@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
	
}
<div class="section-header">
    <div class="title">
        <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
        @T("admin.plugin.brainstation.quickview.help")
    </div>
        
</div>

Thanks for using Bs Quick View Plugin <br/><br/>
You can get help from <a href="http://nop-station.com/Common/Support">Support</a> link 

360test.home/Nop.Plugin.BrainStation.QuickView/Views/BsQuickViewSettings.cshtml
@using Nop.Plugin.BrainStation.QuickView.Models
@using Nop.Web.Framework
@model BsQuickViewSettingsModel
@using Nop.Core.Domain.Seo;
@using Nop.Core.Infrastructure;
@using Nop.Web.Models.Catalog;
@using Nop.Web.Framework.UI

<!--product breadcrumb-->


@{
    Layout = "~/Administration/Views/Shared/_AdminLayout.cshtml";
	
}
@using (Html.BeginForm("Save", "Plugin/QuickView/Settings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
      @Html.AntiForgeryToken()
    <div class="section-header">
        <div class="title">
            <img src="@Url.Content("~/Administration/Content/images/ico-content.png")" alt="" />
            @T("admin.plugin.brainstation.quickview.settings")
        </div>
        <div class="options">
            <button type="submit" name="save" value="save" class="k-button">@T("admin.plugin.brainstation.quickview.save")</button>
            
        </div>
    </div>
    @Html.ValidationSummary(false)
   
    <table class="adminContent">
        
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.EnableWidget") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.EnableWidget)
               
            </td>
        </tr>
<tr>
            <td colspan="2">If you check this opton you will enable the widget of the Bs Quick View plugin. Disabling the checking will make the all settings of Bs Quick View inactive.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>

        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.EnableEnlargePicture") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.EnableEnlargePicture)
               
            </td>
        </tr>
<tr>
            <td colspan="2">If you check this opton you will have a splendid view of enlarged picture on each product box items .After checking & saving it reload your main store page and hover on the product pictures in product box and see the awosomeness.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ShowAlsoPurchased") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ShowAlsoPurchased)
               
            </td>
        </tr>
<tr>
            <td colspan="2">This Option will activate showing the Products which was also purchased with the clicked product on Modal named "Customers who bought this item also bought".</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ShowRelatedProducts") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ShowRelatedProducts)
               
            </td>
        </tr>
<tr>
            <td colspan="2">This Option will activate showing the related Products on Modal.</td>
        </tr>
        <tr>
            <td colspan="2"><hr/></td>
        </tr>
        <tr>
            <td class="adminTitle">
               
                @T("Plugins.BsQuickView.Fields.ButtonContainerName") :
            </td>
            <td class="adminData">
                @Html.EditorFor(model => model.ButtonContainerName)
               
            </td>
        </tr>
<tr>
            <td colspan="2">Provide the class name in which the button "Quick View" will appear. Remember add a '.' before class name . eg(.buttons)</td>
        </tr>

        

        
    </table>

   
}

360test.home/Nop.Plugin.BrainStation.QuickView/Views/QuickViewProductTemplate.Simple.cshtml
@model Nop.Plugin.BrainStation.QuickView.Models.BsQuickViewModel
@using System;
@using System.Collections.Generic;
@using Nop.Core.Domain.Seo;
@using Nop.Core.Infrastructure;
@using Nop.Web.Models.Catalog;
@using Nop.Web.Framework.UI;
@using System.Web.Mvc;
@using Nop.Web.Framework;
@using Nop.Web.Framework.Mvc;
@{
   

    //title, meta
    Html.AddTitleParts(!String.IsNullOrEmpty(Model.ProductDetailsModel.MetaTitle) ? Model.ProductDetailsModel.MetaTitle : Model.ProductDetailsModel.Name);
    Html.AddMetaDescriptionParts(Model.ProductDetailsModel.MetaDescription);
    Html.AddMetaKeywordParts(Model.ProductDetailsModel.MetaKeywords);

    var canonicalUrlsEnabled = EngineContext.Current.Resolve<SeoSettings>().CanonicalUrlsEnabled;
    if (canonicalUrlsEnabled)
    {
        var productUrl = Url.RouteUrl("Product", new { SeName = Model.ProductDetailsModel.SeName }, this.Request.Url.Scheme);
        Html.AddCanonicalUrlParts(productUrl);
    }
}


<div data-productid="@Model.ProductDetailsModel.Id" class="modal modal-static fade quick-view-product-details-modal"  id="quick-view-product-details-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="fa fa-times"></i></button>
                <h4 class="modal-title">@Model.ProductDetailsModel.Name</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-12">
                        

                       


                        <div class="quick-view-product-details-carousal-controller-container">
                            
                            <span class="pull-right">
                                <a class="left-controller" href="#modal-product-picture-carousal" data-slide="prev">
                                    <i class="fa fa-angle-left fa-2x"></i>
                                </a>
                                <a class="right-controller" href="#modal-product-picture-carousal" data-slide="next">
                                    <i class="fa fa-angle-right fa-2x"></i>
                                </a>

                            </span>

                        </div>


                        <div id="modal-product-picture-carousal" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
        
                                @for (int i = 0; i < Model.ProductDetailsModel.PictureModels.Count; i++)
            
                                {
                                    var picture = Model.ProductDetailsModel.PictureModels[i];
                                    if(i==0)
                                    {
                                        @:<div class="item active">
                
                                    }else
                                    {
                                        @:<div class="item">
                                    }
                  

                                    <div class="quick-view-product-details-slide-image">
                                        <img src="@picture.FullSizeImageUrl" alt="@picture.AlternateText" title="@picture.Title" />
                
                                    </div>

                    

                                    @:</Div>
            
                                }
        
        
                            </div>

   

                        </div>


                    </div>

                    <div class="col-lg-7 col-md-7 col-sm-6 col-xs-12">
                        @using (Html.BeginRouteForm("Product", new { SeName = Model.ProductDetailsModel.SeName }, FormMethod.Post, new { id = "product-details-form" }))
                        {
                            <div itemscope itemtype="http://schema.org/Product" data-productid="@Model.ProductDetailsModel.Id">
                                <div class=" product-essential">
                    
                                    

                                    <div class="quick-view-product-details-information">
                                        <!--Price-->
                                        @{
                                            var dataDictPrice = new ViewDataDictionary();
                                            dataDictPrice.TemplateInfo.HtmlFieldPrefix = string.Format("price_{0}", Model.ProductDetailsModel.Id);
                                            @Html.Partial("_QuickViewProductPrice", Model.ProductDetailsModel.ProductPrice, dataDictPrice)
                                        }

                                        <!--product reviews-->
                                        @Html.Partial("_QuickViewProductReviewOverview", Model.ProductDetailsModel.ProductReviewOverview)

                                        @if (!String.IsNullOrEmpty(Model.ProductDetailsModel.ShortDescription))
                                        {
                                            <div class="quick-view-short-description">
                                                @Html.Raw(Model.ProductDetailsModel.ShortDescription)
                                            </div>@:</br>
                                        }
                                        <!--product SKU, manufacturer part number, stock info-->
                                        @Html.Partial("_QuickViewSKU_Man_Stock", Model.ProductDetailsModel)

                                       <!--product manufacturers-->
                                         @Html.Partial("_QuickViewProductManufacturers", Model.ProductDetailsModel.ProductManufacturers)
                                        <!--sample download-->
                                        @Html.Partial("_QuickViewDownloadSample", Model.ProductDetailsModel)
                                        <!--attributes-->
                                        @{         
                                            
                                            var dataDictAttributes = new ViewDataDictionary();
                                            dataDictAttributes.TemplateInfo.HtmlFieldPrefix = string.Format("attributes_{0}", Model.ProductDetailsModel.Id);
                            @Html.Partial("_QuickViewProductAttributes", Model.ProductDetailsModel.ProductAttributes, dataDictAttributes)                
                                        }
                                        <!--gift card-->
                                        @{
                                            var dataDictGiftCard = new ViewDataDictionary();
                                            dataDictGiftCard.TemplateInfo.HtmlFieldPrefix = string.Format("giftcard_{0}", Model.ProductDetailsModel.Id);
                                            @Html.Partial("_QuickViewGiftCardInfo", Model.ProductDetailsModel.GiftCard, dataDictGiftCard)
                                        }
                                        <!-- add to cart-->
                                        
                                        @{
                                            
                            
                                            var dataDictAddToCart = new ViewDataDictionary();
                                            dataDictAddToCart.TemplateInfo.HtmlFieldPrefix = string.Format("addtocart_{0}", Model.ProductDetailsModel.Id);
                                            @Html.Partial("_QuickViewAddToCart", Model.ProductDetailsModel.AddToCart, dataDictAddToCart)                    
                                        }
                                        <div id="quick-view-details-error-message-div"></div>
                                        <div data-product-name="@Model.ProductDetailsModel.SeName" data-productid="@Model.ProductDetailsModel.Id" data-pictureurl="@Model.ProductDetailsModel.DefaultPictureModel.ImageUrl" class="quick-view-details-page-image-and-name-info" style="display: none" ></div>
                                        @*<div class= "form-group row">
                                            @Html.Action("QuickViewProductEmailAFriendButton", "QuickView", new { productId = Model.ProductDetailsModel.Id })

                                            @Html.Action("QuickViewCompareProductsButton", "QuickView", new { productId = Model.ProductDetailsModel.Id })
                                        </div>*@

                                       @Html.Partial("_QuickViewShareButton", Model.ProductDetailsModel)
                        
                                    </div>

                                </div>
                
                               
                            </div>

                        }
                    </div>

                  
                </div>
                <div class="space15px"></div>
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="category-tab quick-view-menu-product-details-nav">
                            <ul class="nav nav-tabs ">
                                @if (!String.IsNullOrEmpty(Model.ProductDetailsModel.FullDescription))
                                {
                          
                                    <li class="active"><a href="#description" data-toggle="tab">Description</a></li>
                                }
                                @if (!String.IsNullOrEmpty(@Html.Partial("_QuickViewProductSpecifications", Model.ProductDetailsModel.ProductSpecifications).ToString()))
                                {

                                    <li><a href="#specification" data-toggle="tab">Specifications</a></li>
                                }
                                @if (!String.IsNullOrEmpty(@Html.Partial("_QuickViewProductTags", Model.ProductDetailsModel.ProductTags).ToString()))
                                {
                                    <li><a href="#tags" data-toggle="tab">Products Tags</a></li>
                                }@if (!String.IsNullOrEmpty(@Html.Partial("_QuickViewProductTierPrices", Model.ProductDetailsModel.TierPrices).ToString()))
                                 {
                                     <li><a href="#tierprice" data-toggle="tab">Special Prices</a></li>
                                 }
                            </ul>


                            <div class="tab-content">
                                @if (!String.IsNullOrEmpty(Model.ProductDetailsModel.FullDescription))
                                {
                                    <div class="quick-view-full-description tab-pane active" id="description" itemprop="description">
                                        @Html.Raw(Model.ProductDetailsModel.FullDescription)
                                    </div>
                                }
                                <div class="quick-view-full-description tab-pane" id="specification">
                                    @Html.Partial("_QuickViewProductSpecifications", Model.ProductDetailsModel.ProductSpecifications)
                                </div>
                                <div class="quick-view-full-description tab-pane" id="tags">
                                    @Html.Partial("_QuickViewProductTags", Model.ProductDetailsModel.ProductTags)
                                </div>
                            
                                <div class="quick-view-full-description tab-pane" id="tierprice">
                                    @Html.Partial("_QuickViewProductTierPrices", Model.ProductDetailsModel.TierPrices)
                                </div>


                            </div> 
                        </div>

                        



                        
                    </div>


                </div>
                <div class="product-collateral">
                    @if (Model.BsQuickViewSettingsModel.ShowAlsoPurchased)
                    {
                        @Html.Action("ProductsAlsoPurchased", "BsQuickView", new { productId = Model.ProductDetailsModel.Id })
                    }
                    @if (Model.BsQuickViewSettingsModel.ShowRelatedProducts)
                    {
                        @Html.Action("RelatedProducts", "BsQuickView", new {productId = Model.ProductDetailsModel.Id})
                    }
                </div>

              
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
          
            </div>
        </div>
    </div>
</div>